services:
  app:
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shaudify
      - SPRING_DATASOURCE_PASSWORD=pass
      - SPRING_DATASOURCE_USERNAME=postgres
    ports:
      - '8080:8080'
  db:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=shaudify
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d
  redis:
    image: redis:7.2-rc-alpine
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass RVFjc2FjYUlXU1VHQldRWSo=
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local