services:
  app:
    build:
      context: .
    container_name: app
    depends_on:
      - db
      - redis
      - minio
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shaudify
      - SPRING_DATASOURCE_PASSWORD=pass
      - SPRING_DATASOURCE_USERNAME=postgres
    ports:
      - '8080:8080'
  db:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=shaudify
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:7.2-rc-alpine
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass RVFjc2FjYUlXU1VHQldRWSo=
    volumes:
      - cache:/data
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9090"
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio-data:/data
volumes:
  cache:
    driver: local
  db-data:
    driver: local
  minio-data:
    driver: local