services:
  app:
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shaudify
      - SPRING_DATASOURCE_PASSWORD=pass
      - SPRING_DATASOURCE_USERNAME=postgres
    ports:
      - '8080:8080'
  db:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=shaudify
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d