spring:
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: localhost
      port: 6379
      password: RVFjc2FjYUlXU1VHQldRWSo=
  datasource:
    url: jdbc:postgresql://localhost:5432/shaudify
    password: pass
    username: postgres
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    show-sql: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
minio:
  bucket: images
  url: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin



